import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Login from "../components/Login";
import { UserProvider } from "@/context/context";
import LoginWrapper from "@/components/Login/wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-dvh bg-white antialiased`}
    >
      <body className="min-h-full flex h-full flex-col">
        <>
        <UserProvider>
          <Header />
          <LoginWrapper children={children} />
        </UserProvider>
        </>
        </body>
    </html>
  );
}
